name: "🐛 Report a bug"
description: "Is something not working as you expect?"
title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!

        Please answer the following. We close issues that don’t.
  - type: textarea
    id: describe-bug
    attributes:
      label: "Clearly describe the bug"
      description: ""
      placeholder: ""
    validations:
      required: true
  - type: textarea
    id: reproduce-bug
    attributes:
      label: "What steps are needed to reproduce the bug?"
      description: ""
      placeholder: ""
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "What did you expect to happen?"
      description: ""
      placeholder: ""
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "What actually happened?"
      description: "For example, what warnings or errors did you get?"
      placeholder: ""
    validations:
      required: true
