name: Lint (callable)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: 'lts/*'
        type: string
      node-version-file:
        description: Node.js version file (takes priority over `node-version` if specified)
        required: false
        default: ''
        type: string
      os:
        description: OS name
        required: false
        default: ubuntu-slim
        type: string

jobs:
  lint:
    name: Lint on Node.js ${{ inputs.node-version-file || inputs.node-version }} and ${{ inputs.os }}

    runs-on: ${{ inputs.os }}

    permissions:
      contents: read

    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js ${{ inputs.node-version-file || inputs.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ case(!inputs.node-version-file, inputs.node-version, '') }}
          node-version-file: ${{ inputs.node-version-file }}
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
