name: Lint (callable)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: latest
        type: string
      node-version-file:
        description: Node.js version file (takes priority over `node-version` if specified)
        required: false
        default: ''
        type: string
      os:
        description: OS name
        required: false
        default: ubuntu-slim
        type: string

jobs:
  lint:
    name: Lint on Node.js ${{ inputs.node-version-file || inputs.node-version }} and ${{ inputs.os }}

    runs-on: ${{ inputs.os }}

    permissions:
      contents: read

    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js ${{ inputs.node-version-file || inputs.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ case(!inputs.node-version-file, inputs.node-version, '') }}
          node-version-file: ${{ inputs.node-version-file }}
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
