name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      node-version: '["16", "18", "20", "22"]'
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      exclude: '[{"node-version": "22", "os": "windows-latest"}]'
      test-options: 'foo bar'

  test-default:
    uses: ./.github/workflows/test.yml
