name: CI

on:
  push:
  workflow_dispatch:

permissions: {} # disable all by default

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      node-version: '["16", "18", "20", "22"]'
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      exclude: |
        [
          {"node-version": "18", "os": "ubuntu-latest"},
          {"node-version": "20", "os": "ubuntu-latest"}
        ]
      test-options: 'foo bar'

  test-default:
    uses: ./.github/workflows/test.yml

  test-node-version-file:
    uses: ./.github/workflows/test.yml
    with:
      node-version-file: .node-version
