name: CI

on:
  push:
  workflow_dispatch:

permissions: read-all # Default. Each job can override this.

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      node-version: '["22", "24"]'
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      exclude: |
        [
          {"node-version": "22", "os": "windows-latest"},
          {"node-version": "24", "os": "macos-latest"}
        ]
      test-options: 'foo bar'

  test-default:
    uses: ./.github/workflows/test.yml

  test-node-version-file:
    uses: ./.github/workflows/test.yml
    with:
      node-version-file: .node-version
