name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
