name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: ./.github/workflows/call-release.yml
    with:
      publish: false
      draft: false
    permissions:
      contents: write
