name: Release PR

on:
  workflow_dispatch:
    inputs:
      new-version:
        description: New version to release
        required: true
        type: choice
        options: [patch, minor, major]

jobs:
  release-pr:
    uses: ./.github/workflows/call-release-pr.yml
    with:
      new-version: ${{ github.event.inputs.new-version }}
    permissions:
      contents: write
      pull-requests: write
