name: Test

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: '["18", "20", "current"]'
        type: string
      os:
        description: OS name
        required: false
        default: '["ubuntu-latest"]'
        type: string
      exclude:
        description: Exclude from matrix
        required: false
        default: '[]'
        type: string
      test-options:
        description: Options to pass the test command
        required: false
        default: ''
        type: string

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # NOTE: The `strategy` property is not fully supported, so it uses `fromJson()`.
        #       For details, see https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2
        node-version: ${{ fromJson(inputs.node-version) }}
        os: ${{ fromJson(inputs.os) }}
        exclude: ${{ fromJson(inputs.exclude) }}

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # NOTE: npm v10 has dropped support for Node.js v16.
      - name: Install npm v9
        if: ${{ startsWith(matrix.node-version, '16') }}
        run: npm install --global npm@9 && npm --version

      - name: Install latest npm
        if: ${{ !startsWith(matrix.node-version, '16') }}
        run: npm install --global npm@latest && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test --ignore-scripts -- ${{ inputs.test-options }}
